### ISSUE TITLE
Expose trajURL parameter in analytics

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#153]
## Use Case
When a user loads a trajectory by URL, e.g. with a link like https://simularium.allencell.org/viewer?trajUrl=https://aics-agentviz-data.s3.us-east-2.amazonaws.com/trajectory/nanoparticle_wrapping.simularium, it would be nice to capture the value of the trajURL param, in this example https://aics-agentviz-data.s3.us-east-2.amazonaws.com/trajectory/nanoparticle_wrapping.simularium, so that we can list the links that were used for a given period of time.

## Solution

We already have access to the URLs in the analytics, but would be nice to make it easier to browse the trajURL params as a category.

## Acceptance Criteria

We should be able to list the trajURL param values that users used over a requested time period, e.g. in a given month.

**Comment by thao-do** [comment]
The following are added into the [analytic report](https://datastudio.google.com/u/0/reporting/5049a3ba-fddb-4a05-8654-1cff5e47c2ae/page/X1RrB):
1. `trajFileName` value under Event Action `loaded from list`, triggered by pageview or history changes with page URL containing "trajFileName"
2. `trajUrl` value under Event Action `loaded from URL` , triggered by pageview or history change with page URL containing "trajUrl"

Note: 
- to separate the file loaded from list and URL, I had updated the generic Event Action `File loaded` to `loaded from list` and `loaded from URL`, so in the report you might see the old generic Event Action `File loaded` 
- you can sort a column by clicking on the column title
- you can see the latest update time shown in the bottom left corner of the report page
