### ISSUE TITLE
Add "About" item to help dropdown with software versions

### ISSUE THREAD

**Issue by schoinh** [simularium/simularium-website#164]
Originally submitted by @blairlyons 

## Use Case

It would be nice for users and developers to be able to quickly check the version of the modules they are currently using.

## Acceptance Criteria

A user can see the version of the website, viewer, and engine that they are currently using.

## Details

- Add "About" item to end of help dropdown list on simularium website viewer page
- when clicked or hovered, a small menu opens. This could follow the same style as the submenu for "Submit issue". Menu contains:
    - Website v1.0.151
    - Viewer v2.9.1
    - Engine v?
    - version numbers link to the release page where release notes will be added, e.g. https://github.com/allen-cell-animated/simularium-website/releases/tag/1.0.151

**Comment by schoinh** [comment]
How do we make sure the version numbers are always up-to-date and match what's really on prod? Is this something that can be automated?

**Comment by blairlyons** [comment]
I'd guess there'd be variables for website and viewer that are set on build from the package version, and then the engine version can show up once connected to the backend, hopefully there's a way to ask the backend what version it is
