### ISSUE TITLE
Plots panel gets cluttered/obscured with scroll bars

### ISSUE THREAD

**Issue by schoinh** [simularium/simularium-website#165]
## Description

Plots panel gets cluttered/obscured with scroll bars when the user's operating system has scroll bars set to always visible.

## Expected Behavior

Scroll bars should not obscure plot panel contents in any scenario. Either add whitespace to the right of the plots or do some sort of smart scrollbar detection (probably difficult).

Slack discussion: https://allencellscience.slack.com/archives/CFT511CE4/p1621523250002500

## Reproduction

1. On a Mac, set your OS settings so that scroll bars are always visible
2. Go to simularium.allencell.org/viewer and load a trajectory with many plots, like endocytosis
3. Scroll bars obscure/clutter the plot panel

**Comment by blairlyons** [comment]
This can be fixed by setting scrollbars to fade, priority too low
