### ISSUE TITLE
Implement agent color picker in left panel

### ISSUE THREAD

**Issue by schoinh** [simularium/simularium-website#169]
Originally submitted by @blairlyons 

## Use Case
When a user has a model loaded in the viewer, it would be nice if they could adjust the color for an agent type.

## Acceptance Criteria
In the left panel, clicking the color swatch next to an agent type or state opens a palette to set the color.

## Details
This depends on the color picker design https://github.com/allen-cell-animated/simularium-website/issues/196
Also requires colors being added to .simularium files in order to have test data (allen-cell-animated/simulariumio#39), and requires a function for setting colors to be exposed in the Viewer (allen-cell-animated/simularium-viewer#148)

**Comment by blairlyons** [comment]
duplicate
