### ISSUE TITLE
Color picker design

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#196]
## Use Case

It would be nice if a user could select an agent color swatch and use a color picker to set the color of all agents of that type.

## Acceptance Criteria

A user can choose a color and assign it to a type of agent in the Viewer UI.

## Details

Clicking a color swatch next to an agent in the left panel of the Viewer UI could bring up a small menu.

It would be ideal to provide presets and palettes to avoid overwhelming the user or ending up with bad color combos. 

This would ideally be coordinated with the color options provided to computational users of simulariumIO when they are setting colors in their data (https://github.com/allen-cell-animated/simulariumio/issues/39), i.e. so they have the choice of the same presets to streamline colors across models.

## Documents
[**Link to Design Brief**](https://docs.google.com/document/d/1LL5_9avSMUkO4He1BfNwEnGcipGZV7rs679Zp2QUl_Y/edit)

**Comment by lynwilhelm** [comment]
[Link to Design Brief](https://docs.google.com/document/d/1LL5_9avSMUkO4He1BfNwEnGcipGZV7rs679Zp2QUl_Y/edit)

**Comment by lynwilhelm** [comment]
@blairlyons I don't know how this UX ticket ended up in the backlog again but I just pulled it and placed it in my "done" column.

**Comment by blairlyons** [comment]
oh probably got reopened from moving to a new project board. I'll close it
