### ISSUE TITLE
Warn user about inconsistent timestep

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#238]
## Use Case
For a model with inconsistent timestep, if you click on the time bar to skip ahead before playing, the time bar hangs and does nothing. It would be nice to notify the user that this is why the time bar is hanging while we work on fixing this issue.

## Acceptance Criteria
Once inconsistent timesteps can be detected (i.e. after an inconsistent frame arrives), a popup should warn the user.

## Details
Popup could say something like: "Detected inconsistent timesteps, some features may not work as expected. We're working on this."

Example model with inconsistent timestep https://simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/medyan_actin_only.simularium

Current behavior (issues a user may encounter)
1. Load example model
2. Click the play button, then click a later point in the time bar, the playback skips to later in the trajectory (although it seems to go halfway as far as you clicked? e.g. goes to ~550 when I click ~850 but depends on the current time)
3. Reload
4. Without clicking the play button, click a later point in the time bar, the time bar spins forever

A sample of the times in this trajectory:
```
 0.00000e+00 1.00000e+00 2.00000e+00 3.05000e+00 4.10000e+00 5.15000e+00
 6.20000e+00 7.25000e+00 8.25000e+00 9.25000e+00 1.02500e+01 1.12500e+01
 1.22500e+01 1.32500e+01 1.42500e+01 1.52500e+01 1.62500e+01 1.72500e+01
 1.82500e+01 1.92500e+01 2.02500e+01 2.12500e+01 2.22500e+01 2.32500e+01
 2.42500e+01 2.52500e+01 2.62500e+01 2.72500e+01 2.82500e+01 2.92500e+01
 3.02500e+01 3.12500e+01 3.23000e+01 3.33500e+01 3.44000e+01 3.54500e+01
```

**Comment by schoinh** [comment]
Ooh, this might be a big task. Much of the frontend code assumes a constant timestep size for a given trajectory. @EricJIsaac does the backend also assume a constant timestep?

**Comment by schoinh** [comment]
Looks like the test file used in the repro steps above has a `timeStepSize` of 1.0 under `trajectoryInfo`, which is also inconsistent with the actual time data. Seems like another great topic for a meeting 😄

**Comment by blairlyons** [comment]
dealing with inconsistent timesteps is another issue https://github.com/simularium/simularium-planning/issues/25
