### ISSUE TITLE
Do users understand what the focus button does and why and when to press it?

### ISSUE THREAD

**Issue by schoinh** [simularium/simularium-website#247]
## Use Case

I was testing that the camera controls were working after a viewer version bump, and found myself confused by the Focus button because the button's color when turned off and turned on are too similar. I think I only figured out how it was working eventually because I know how it's supposed to work, so I think it would be even more confusing for actual users.

## Acceptance Criteria

A user is able to successfully focus on an agent, and turn focus off to rotate the camera while the simulation is playing. 

## Details/Ideas

When Focus mode is turned on, the button color should be significantly brighter (or different in some way that indicates "on") than when it is off. 

Maybe a good color for the "on" state would be the current hover color. And maybe we could also implement the same color scheme to the rotate/pan buttons.

**Comment by blairlyons** [comment]
related to this issue https://github.com/allen-cell-animated/simularium-website/issues/279

**Comment by lynwilhelm** [comment]
I have a few hypotheses about why people are confused about it being on vs off.

- Focus is on by default, but the tooltip reads "Focus", which may lead people to think that is a positive action and that if they click they are applying the "focus" behavior.
- "Off" state styling of the Pan button just above is slightly different and on/off styling in general needs strengthening
- "Focus" is tooltip language used in both switching on and off
- Besides the word "focus" there is no indication of what this button does, or that it is tied to another action the user must take to see the resulting behavior
- When the player is not actively advancing a simulation and a user toggles the button, the result cannot be viewed. It's a mystery button
