### ISSUE TITLE
Option to loop movie

### ISSUE THREAD

**Issue by mattakamatsu** [simularium/simularium-website#267]
## Use Case

_Please provide a use case to help us understand your request in context_

Hi. I am using the endocytosis simulation in talks and to introduce people to my work. I find myself wishing that I could loop the animation and stare at it, for presentation and hypothesis-generating reasons.

## Acceptance Criteria

_Please describe how you know this is done_

If there's a flag or button in which we can toggle whether or not to loop the animation

## Details

_Please provide any helpful specifications_

**Comment by schoinh** [comment]
Thanks for your input! That definitely sounds useful. We'll discuss how to prioritize and implement this in one of our meetings soon.

**Comment by blairlyons** [comment]
Design is done, implementation is tracked here https://github.com/simularium/simularium-website/issues/298
