### ISSUE TITLE
View and edit current camera transform

### ISSUE THREAD

**Issue by mattakamatsu** [simularium/simularium-website#276]
## Use Case
It would be nice if users could view and edit the current camera transform.

## Acceptance Criteria
A user can choose to display or hide the current camera transform, and they can edit the values and see the view update.

## Details
camera transform includes: camera position, look at position, up vector, and field of view

Likely will want a hotkey to bring this up too.

This data is currently saved in .simularium files for the initial view and the view that the home btn returns to.

Original details from Matt:

Hello,

I was making a video recording of a simulation and ended up taking screnshots at each time point. I would play the entire stitched movie recording and then realize that my choice of view rotation or zoom was too severe at e.g. time point 10, so then I would go back to that time point and try to make new screenshots from then on.  
It would have been really helpful if I could have recorded (or seen) the viewer coordinates - i.e. xyz rotation zoom type of information. Then at the very least I could manually go back to a similar view to go back and record the next frame.  Even better would be if I could input these viewer coordinates to snap to that view. Then, I could send someone the simularium link to my simulation, which would be rotated and zoomed to a particular part of the simulation, and then say "hey look at frame 17 at this view, isn't it weird that Hip1R is in that position, what do you think?"  
In cytosim I have access to the viewer coordinates by paging through some state information in the visualization (e.g. press "h" to scroll through current settings on object color, size, and the viewer) or in a context menu (right click/export view). and then I have the option of setting an initial view in the config text file. 

I wonder if this information is part of the json file? Then I wouldn't mind including viewer coordinate info in my json file when I load it into simularium. Thanks!!

![Screen Shot 2021-11-07 at 2 12 31 PM](https://user-images.githubusercontent.com/16111930/140663776-594d8c50-e60c-4359-8933-ebb0f1016d6c.png)
![Screen Shot 2021-11-07 at 2 11 23 PM](https://user-images.githubusercontent.com/16111930/140663780-1b9f3212-79dd-43ff-a4be-7133cd0b5f80.png)

**Comment by toloudis** [comment]
We've discussed being able to have pre-captured flythroughs or possibly per-frame camera positions that can be interpolated but that is a "big" feature that has to have a lot of details thought out.

We have a debugging-only headup display on the viewer that we might be able to repurpose for camera coordinates.  Then you could both display and type in the relevant values, and hide the controls when done.

It would also be interesting to see something like `&t=17` in the url, like you can do with youtube links, to have the playback start at a particular time.

**Comment by mattakamatsu** [comment]
Hi Dan, thanks for letting me know -- no rush on that.  It would totally work for me to instead have access to an alternate debugging viewer for that purpose.

**Comment by blairlyons** [comment]
Thanks for the issue @mattakamatsu, I added some more detail. Like @toloudis says, setting keyframes and interpolating between them during playback is a larger task, but we should be able to get this part done in the near future, so you can at least view and edit the current settings.

**Comment by mattakamatsu** [comment]
Okay, great! Good to know that we can include view information in the simularium input file.

**Comment by lynwilhelm** [comment]
**DESIGN BRIEF**

**Problem Statements**

- 

**Project Goals**

- 

**What we will NOT do**

- 

**How will we know we are done?**

- Team feedback is complete and file is ready for dev handoff

**How will we measure success?**

-
