### ISSUE TITLE
Implement Export Data (Download)

### ISSUE THREAD

**Issue by lynwilhelm** [simularium/simularium-website#295]
## Use Case
Users need ability to download a trajectory

## Acceptance Criteria
Add download "button" to UI
User agent handles the download

## Details
Subsequent downloads filename will end in (1), (2), (3), etc (not sure if this is standard behavior across all browsers, but this is important so users can save differentiate versions as they apply changes)

Design Link: https://xd.adobe.com/view/75b6a3c8-f650-443b-bccc-d1fcd134a35e-20e5/

More details about how to implement with the backend functionality TBD [here](https://github.com/simularium/octopus/issues/27)

**Comment by blairlyons** [comment]
@lynwilhelm is there a design link ready for this one?

**Comment by lynwilhelm** [comment]
Design link added. Thanks, @blairlyons

**Comment by interim17** [comment]
What user changes should be captured in the downloaded trajectory?

**Comment by interim17** [comment]
@lynwilhelm @blairlyons 
I have a working V1 of this but my hiccup is understanding the bit about capturing user changes, and file locations for fetching networked files. Even if my current approach works it will need updating in relation to [Alli's PR ](https://github.com/simularium/octopus/pull/35)when we switch to Octopus.

In my current version a local Simularium file or a networked file stored in our AWS data bucket can be downloaded. Blair, some gaps in my understanding about user-changes and file-locations might be suited for a Simularium walkthrough part two?
