### ISSUE TITLE
Resolve Issues with Tooltips (and labels)

### ISSUE THREAD

**Issue by lynwilhelm** [simularium/simularium-website#297]
## Use Case
1. Users cannot easily select/deselect stars and checkboxes because tooltips block ability to interact with the one directly above
2. Users need to be able to quickly identify what elements make up the agent panel and actions they can perform.
3. The star with text “SHOW TYPE” meant to serve as labels to columns below, do not read as labels to columns and cause confusion.

## Acceptance Criteria

1. Immediate timeout on tooltips when exiting star/checkbox
2. New tooltip does not show after a user clicks star/checkbox (only show on initial hover/focus)
3. Line with star icon, SHOW, TYPE is completely removed
4. "All" checkbox label is changed to "All Agent Types"

## Details

Design Link: https://xd.adobe.com/view/75b6a3c8-f650-443b-bccc-d1fcd134a35e-20e5/

**Comment by blairlyons** [comment]
@lynwilhelm Is there a design link to add to this?

**Comment by lynwilhelm** [comment]
Yes, design link just added. Thanks!
