### ISSUE TITLE
Implement Version Info

### ISSUE THREAD

**Issue by lynwilhelm** [simularium/simularium-website#304]
## Use Case

Users and developers cannot quickly check the version of the modules they are currently using

## Acceptance Criteria

Add menu item under "Help" for Version info
Clicking new menu item will initiate a modal with that info
Repo name/version are linked to respective repos

## Details
The app versions are already being logged out here: https://github.com/simularium/simularium-website/blob/main/src/index.tsx#L90-L92

Style of modal is consistent with what exists today
[Design Link](https://xd.adobe.com/view/1f95e015-aded-4323-9cc9-a5be920fc8be-4ac6/)

**Comment by interim17** [comment]
@lynwilhelm the design for this ticket shows two buttons `Cancel` and `Close` But the modal just displays information, the only action a user can take is to close it, so I think it two buttons is redundant. Good to implement with just one?

**Comment by interim17** [comment]
@lynwilhelm @toloudis question for y'all about engines. The UX design shows three pieces of information: viewer version, website version and engine. Placeholder in design for engine is "not connected to server" 

Can someone clarify what is meant by engine in this case? Should I be pinging the backend to get the version of the simularium engine C++ application?

Currently we are logging website version, viewer version, and website build, but nothing to do with the engine.

**Comment by interim17** [comment]
@toloudis thanks for clarifying.
@meganrm @lynwilhelm I propose to knock this little ticket out without the engine info, and just show version info for Viewer and Website, and then add the engine bit to the list of things that get addressed when we make the switch to Octopus
