### ISSUE TITLE
Automatically focus in input box when "Load by URL" modal opens

### ISSUE THREAD

**Issue by schoinh** [simularium/simularium-website#322]
## Use Case

As a Simularium user, it would be more convenient/less annoying if my cursor automatically focused in the input box when the "Load by URL" modal opens. Currently, I have to click in the text input box to focus before I can paste my URL.

## Acceptance Criteria

When the user clicks on the "Load Model -> From a URL" menu item to open the Load by URL modal, they can hit ctrl/cmd + V immediately afterwards to paste a URL into the text input box, without having to click inside the input box to focus the cursor first.

## Details

There is an `autofocus` prop that can be added to an Antd `Input` component that _should_ work, but it doesn't. That might be a bug with Antd.

**Comment by frasercl** [comment]
Resolved by #373
