### ISSUE TITLE
Example blood plasma without HIV PDB trajectory

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#326]
## Use Case
As a biologist considering using Simularium, I would like to see an example trajectory of PDB geometries so I can imagine how useful it will be to use the viewer with my system and structures.

## Acceptance Criteria
.simularium file(s) for an example blood plasma (without HIV) trajectory with all (or almost all) agents rendered as PDB.

## Details
cellPACK blood plasma without HIV

**Comment by meganrm** [comment]
https://simularium.allencell.org/viewer?trajUrl=https://www.dropbox.com/s/w7ntn75j53cth8p/BloodPlasma.simularium?dl=0

**Comment by blairlyons** [comment]
TODO: apply rendering adjustments from Graham's settings with @toloudis

**Comment by meganrm** [comment]
@megan: add spike proteins to HIV

**Comment by meganrm** [comment]
![Uploading BloodPlasma default AO setting recommended by GJ_v1.png…]()

**Comment by toloudis** [comment]
@meganrm can you re-upload that png file? the link seems totally broken

**Comment by meganrm** [comment]
https://allencellscience.slack.com/archives/CMQFRJPPF/p1647365908359869?thread_ts=1647365343.259029&cid=CMQFRJPPF

**Comment by toloudis** [comment]
<img width="1750" alt="BloodPlasma default AO setting recommended by GJ_v1" src="https://user-images.githubusercontent.com/2193409/163281433-6d618a23-7579-439c-94f2-512a7711e729.png">

**Comment by toloudis** [comment]
In the trajectory file, we have Errors fetching:
https://files.rcsb.org/download//EMD-5239.map.cif
https://files.rcsb.org/download//EMD-5241.map.cif

**Comment by meganrm** [comment]
yeah, i'm going to replace those with objs I think

**Comment by jsavieo** [comment]
Remaining work:

- Make a version of blood plasma without HIV
- Convert ldl into objs
- Need release of viewer with ao updates
- Change nightly to use main branch

**Comment by meganrm** [comment]
https://staging.simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/json_v3/blood-plama-pdb.simularium

It's hard to tell, but there is some overlap with the pdbs. This is because the pdbs aren't centered on the collision sphere trees. Also the `iIgA_Antibody_2mer` sphere tree is too large, leading to big gaps in the packing.

For comparison, the sphere trees:
https://staging.simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/json_v3/blood-plasma-sph.simularium

**Comment by jsavieo** [comment]
- Need to figure out how pdbs were centered from Ludo
- Make new issue with next steps for next sprint

**Comment by blairlyons** [comment]
just updated viewer on staging, so it has the AO updates

**Comment by meganrm** [comment]
update, loading on staging, need to release to production to have it work on the main site : https://staging.simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/json_v3/bloood-plasma-1.0.simularium

**Comment by meganrm** [comment]
https://simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/json_v3/bloood-plasma-1.0.simularium
