### ISSUE TITLE
Update Overview figure on Simularium homepage

### ISSUE THREAD

**Issue by thao-do** [simularium/simularium-website#328]
## What needs to happen?

Update the overview image on the homepage. I've split that image to 2, we can stack them (simularium-overview.png first then simularium-agent-rep.png) or sandwich a chunk of text with them (the chunk that starts with "Current object representation options..." and ends before "Planned for future"). 

## Why should we do this?

This image has been updated in the submitted paper and we want to match that. 

## When does this need to get done?
Before the paper is published. 

## Assets

Simularium overview
> ![simularium-overview](https://user-images.githubusercontent.com/25212364/157302971-56d09bd7-56b9-43da-a716-d312075ec219.png)

Agent rep
> ![simularium-agent-rep](https://user-images.githubusercontent.com/25212364/157302964-158960b0-7e3d-4ece-8d88-f3bd49a12cb1.png)

**Comment by schoinh** [comment]
Confirmed with @blairlyons we don't need to sandwich text between the 2 new images, will keep layout as is.
