### ISSUE TITLE
Update landing page meta tags (image, title, description, etc.)

### ISSUE THREAD

**Issue by thao-do** [simularium/simularium-website#335]
## What needs to happen?
Update the open graph (og) meta tags: 
`og:title`: Simularium
`og:description`: The Simularium Viewer makes it easy to share and interrogate interactive 3D visualizations of biological simulation trajectories and related plots directly in a web browser.
`og:image`: tbd, maybe this? 

<img width="600" alt="Screen Shot 2022-04-04 at 2 50 18 PM" src="https://user-images.githubusercontent.com/25212364/161638173-f549c78f-5589-4249-bf35-e04af00c2a6d.png">

## Why should we do this?
On social media platforms (Twitter, Facebook, LinkedIn, Slack, etc.), when a person type the link "simularium.allencell.org", a social card will be generated automatically and displayed together with the link in the post/message.

We'd like to have relevant information displayed properly to encourage interactions.

Examples:
<img src="https://user-images.githubusercontent.com/25212364/161638912-cf9928ea-24a7-4779-bcb4-aa3cdd8ee09c.png" width="380"> 

or 
<img src="https://user-images.githubusercontent.com/25212364/161638929-13de6e47-eea3-4292-91ad-b7a3c5991a67.png" width="380">

## When does this need to get done?
During regular maintenance update; ideally before Communication initiates the Google Ads for Simularium at the end of April.

**Comment by blairlyons** [comment]
due date: 4/25
