### ISSUE TITLE
Load via URL is broken on staging

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#344]
## Description
Files do not load via URL on staging

## Expected Behavior
Files should load on staging now, both binary and JSON, regardless of whether they are from a URL or local file.

## Reproduction
[Prod works](https://simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/nanoparticle_wrapping.simularium)

[Staging does not](https://staging.simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/nanoparticle_wrapping.simularium)

## Environment
Testing in Firefox on staging running simularium-website 3997ebf

**Comment by toloudis** [comment]
Just as a hint, I did see this issue at one point and fixed it.  I believe this _should_ be fixed if staging had the absolute latest viewer and website.  Can test locally.

**Comment by toloudis** [comment]
Nevermind the above, I just checked and it seems to be a real bug.  The last website update seems to have missed this load via url case.  It's passing the wrong type down into the viewer.  The viewer expects to see a ISimulariumFile object but it's getting a json object.
