### ISSUE TITLE
Add optional fields to autoconversion UI

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#346]
## Use Case
As a user with data from a supported simulation engine, I want to load a file from the external engine without having to convert in Python first, and instead provide my data through a UI **including additional options in the UI, e.g. color and metadata**.

### File(s) from any of the simulation engines supported by simulariumio can be loaded locally in the Viewer

- [ ] Implement modal content with preexisting responsive/flexible framework (consult with me on any questions/concerns)
- [ ] #396
- [ ] #405
- [ ] #406
- [ ] #407
- [ ] Implement icons specified from ant design

## Details
[Link to final designs](https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/)
Design task https://github.com/simularium/simularium-website/issues/355

A minimal part of the design was implemented in [this issue](https://github.com/simularium/simularium-website/issues/414).

**Comment by meganrm** [comment]
@blairlyons and @ascibisz have the templates been updated in simulariumio to match the wording on these design documents? And what files formats should be supported in this set of work. Is it still just smyoldn?
