### ISSUE TITLE
Design for autoconversion UI

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#355]
### Background
We are allowing Readdy and cytosim file types to be auto converted into .simularium for ease of use

### User needs statement(s)
As a computational scientist, I want to load my own data without writing a Python script and instead use a UI to provide a file and enter additional info so that I can write one less script.

### Size [xs, sm, m, lg, xl]
_Expected level of user research (includes discovery) and design effort_
Medium

### Requirements
- A UI that fits into current experience that supports intake of information related to the file (different template for each file type)
- A path by which users can convert and upload non-.simularium files to .simularium file type and load into the viewer (smoldyn, cytosim, cellPACK, SpringSaLaD will be supported with this release)
- A way to logically present hierarchy, required and non-required fields, description and help text as needed in the template/form

### Deliverables (acceptance criteria)
- UI + Interaction design
- Thoughtful review team and internal stakeholders and users for feedback

### Stakeholder(s)
Megan, Blair, Graham, Matt A (has his cytosym files but maybe not necessary to review with)

## Use Case
As a user, I want to load my own data without writing a Python script and instead use a UI to provide a file and enter additional info.

## Acceptance Criteria
Designs ready for development of production autoconversion UI #346

## Details
Each engine that we support has it's own required data fields. Templates for the fields for each can be found [here](https://github.com/simularium/simulariumio/tree/main/ui-templates)

The prototype UI will be a good reference https://github.com/simularium/simularium-viewer/issues/237

**Comment by meganrm** [comment]
Unstyled smoldyn example form: 

<img width="744" alt="Screen Shot 2022-08-16 at 11 39 49 AM" src="https://user-images.githubusercontent.com/5170636/184954410-3b9c7591-4b58-4eaf-a3db-721ccedec43b.png">
<img width="1092" alt="Screen Shot 2022-08-16 at 11 40 22 AM" src="https://user-images.githubusercontent.com/5170636/184954503-cfbbf406-3530-4788-9b35-16c9551fe466.png">
