### ISSUE TITLE
Mesh or pdb not loading into Simularium Viewer

### ISSUE THREAD

**Issue by MargotRiggi** [simularium/simularium-website#381]
## Description
I've tried to use the example python code for converting a SpringSalad simulation trajectory into the Simularium accepted format, and I was able to drop the resulting file into the viewer just fine. However, when I've tried to add the code for specifying a PDB or OBJ files (from their path on my computer), the code still run correctly (I didn't get any error message), but upon dropping the converted file into Simularium viewer, I get an error message saying that the mesh couldn't be loaded (if using an obj) or the file couldn't be fetch (if using pdb) 

## Expected Behavior

_What did you expect to happen instead?_

## Reproduction

_A minimal example that exhibits the behavior._

## Environment
* simulariumio Version:1.6.3
* Python Version:13.0.1
* Operating System:MacOS Monterey v12.2.1

**Comment by meganrm** [comment]
The paths to the files have to be either full urls of where the geometry is hosted (AWS, raw GitHub, public Dropbox), OR just the file name, and drag and drop all the files together onto the viewer at once (both the simularium file and the OBJ files). We can't access your hard drive from the browser. 
We're working on a more user friendly way to input the files and the geometry together. 
Sorry for the confusion, thanks for the question, let us know if it still doesn't work

**Comment by MargotRiggi** [comment]
Yup, it works now! Sorry for my misunderstanding of the tutorial and thank you for your quick reply!
