### ISSUE TITLE
Update content in left panel on Simularium (when no trajectory is loaded)

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-website#386]
## Use Case

When a trajectory isn't loaded in the viewer we want to have useful information showing for the user 

## Acceptance Criteria

Content on the left planet should match the content in the [linked design](https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/screen/6066a8cf-b769-4c53-adae-873f9af9dc68)

**Comment by blairlyons** [comment]
https://github.com/simularium/simularium-website/pull/391
