### ISSUE TITLE
[Auto-conversion]-Implement full screen processing overlay (including header) with ability to stop and go back to form, cancel process, and open a new simularium instance in a new tab

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-website#390]
Overlay while the file is being converted

[link to design](https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/screen/5203d8f8-e75f-4d75-800c-82445583cd0e/)

**Comment by interim17** [comment]
Design question. @lynwilhelm 

[Design here](https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/screen/5203d8f8-e75f-4d75-800c-82445583cd0e/specs/) shows semi-transparent overlay on top of viewer screen. It is also shown in sequence of previous modal based designs.

In the current design the input form is full screen, not modal, so I assume that the transparent processing overlay should reveal the [input form page](https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/screen/4e72b109-7f4d-472e-99d5-2e0e1d53569d/) behind it and not the viewer screen. Please correct me if that's wrong.
