### ISSUE TITLE
"Load model" menu item titles are updated

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-website#394]
**Acceptance criteria:**

1. Load model has 3 items as shown in design: 
[Link to design](https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/screen/15e9b709-ab6c-469d-85ac-893a8147d326/)
2. Clicking "Import other file type" changes the viewer state to a new status, "IMPORTING"

**Comment by lynwilhelm** [comment]
Is there a way to visually “clear it out” but preserve it so if the user cancels they are returned to previous state?
