### ISSUE TITLE
[Auto-conversion] - Production Autoconversion UI without optional fields

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-website#414]
## Use Case
As a user with data from a supported simulation engine, I want to load a file from the external engine without having to convert in Python first, and instead provide my data through a UI. This version will only include the:
1. engine type
2. file
3. trajectory name? (we could just display the file name)

#### Any additional information needed from the user but not contained in the file(s) can be entered in a UI
- [x] #394
- [x] #395

#### User feedback and control
- [x] #390
- [x] #389
- [x] #408
- [x] #387

#### Convert the file using octopus 
- [x] #458
- [x] #459

**Comment by meganrm** [comment]
@lynwilhelm please review the second section and delete any issues you don't think are needed for the bare bones version

**Comment by lynwilhelm** [comment]
@interim17 @meganrm @blairlyons

I added a new section to the designs with just 2 slides to show what an "MVP" version would look like. You can find the link for it on the first Table of Contents page. https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/

All work items above still apply except #395 could be changed to describe the Trajectory Title input as the only optional display data field to keep. Also, I think #389 could be postponed until later version as well. If there is an issue, the user will just get the generic error message.
