### ISSUE TITLE
Preserve time in URL so user can share

### ISSUE THREAD

**Issue by lynwilhelm** [simularium/simularium-website#418]
## Use Case

As a user, I want to share a trajectory at a specific time point with another user via a URL so that I can point out something about the state of the simulation at a specific time.

## Acceptance Criteria

- Time can be preserved in URL string
- UI design and interaction design implemented as specified in designs
- Time units used in string must be vetted with team

## Details

[Link to Designs](https://www.figma.com/file/9i8Dphcfp3t7e7TouwNheB/Simularium-share-time?type=design&node-id=96%3A1941&t=QsNFwDZNp1jK6BLw-1)

**Comment by lynwilhelm** [comment]
@interim17 Yes on tooltip with aligned styling and I've updated the URL above to be the developer link instead of review mode link. Thanks so much!

**Comment by interim17** [comment]
@lynwilhelm i'm going to make the input box where users specify their desired time stamp larger than shown in the design because i'm noticing that that are some large numbers as possible values (5+ digits) and they are cut off at the current width of 51 pixels

**Comment by blairlyons** [comment]
duplicates https://github.com/simularium/simularium-planning/issues/113
