### ISSUE TITLE
Load model menu: examples cover simularium file option

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-website#438]
## Description

When I try to get to the "Simularium file" drop down in the "load model" menu on the staging/dev setup the example models menu covers the second menu item. I think this has been caused by the additional buttons to the right of the "load model" dropdown

## Expected Behavior

On the production site, the submenu is to the side of the dropdown. 

## Reproduction
First image shows production/expected behavior. Second image is from what's current on `main`

<img width="825" alt="Screenshot 2023-10-05 at 11 33 38 AM" src="https://github.com/simularium/simularium-website/assets/5170636/efb4c9ee-77f0-4499-add1-2d5f2ed40755">
<img width="836" alt="Screenshot 2023-10-05 at 11 33 45 AM" src="https://github.com/simularium/simularium-website/assets/5170636/905e55f5-9288-479c-b224-eb1e7d36f9fa">

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

**Comment by meganrm** [comment]
One possible solution: add "from examples" as a third option to the modal instead having a dropdown at all. 
<img width="681" alt="Screenshot 2023-10-05 at 1 31 56 PM" src="https://github.com/simularium/simularium-website/assets/5170636/46d7a664-666f-405b-9d31-6a665fcf2461">

**Comment by blairlyons** [comment]
@lynwilhelm can we just move the menu to the left?

**Comment by meganrm** [comment]
I have fixed it, but I still think it's now weird to have a flyout that is so much larger than the initial menu

**Comment by lynwilhelm** [comment]
@meganrm @blairlyons I see this just got closed and the current fix makes sense for now. A pattern for wrapping long text to a new line and max width and a more obvious "active" styling state for the menu (like background color change) would improve the menu design. We can add that to the backlog anytime we want and it would be an easy/quick piece of work.
