### ISSUE TITLE
Viewer button icons and styling are funky

### ISSUE THREAD

**Issue by lynwilhelm** [simularium/simularium-website#446]
## Description

_A clear description of the bug_
I am reporting this as a bug because it didn't fit into another issue category
The viewer buttons look a bit funky and are a little different than the design intent. Joe and I discussed this a while back and he is aware, I just wanted to make a ticket so we don't forget about it.

- Border color is not accurate (too bright). The border color should be #6e6e6e. 
- There are new icons for many of these that were created by Thao
- Ortho and perspective icons do not have enough padding in the button.
- You can view spacing in the design file, but general guidance is 5px minimum padding between icons and button edge.

https://xd.adobe.com/view/75b6a3c8-f650-443b-bccc-d1fcd134a35e-20e5/
Please reach out if there are any questions! Thanks, Joe!

## Expected Behavior

_What did you expect to happen instead?_
![Screenshot 2023-11-06 at 3 05 27 PM](https://github.com/simularium/simularium-website/assets/93954795/604d109a-9de2-4257-85ac-ccfcfe9aaa62)

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

**Comment by meganrm** [comment]
closed by https://github.com/simularium/simularium-website/pull/478
