### ISSUE TITLE
Load from url input is right justified

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-website#464]
## Description

The "load from url" text input is formatted weirdly: it's right justified which is confusing. 

<img width="780" alt="Screenshot 2024-02-14 at 5 57 12 PM" src="https://github.com/simularium/simularium-website/assets/5170636/aea09128-4a43-4423-86ba-3edb35f595e7">

## Expected Behavior

I think this is the [design](https://xd.adobe.com/view/5f448466-eebd-4ad2-bdd8-314a55133403-0a17/screen/42683ba6-2c6e-4133-80e1-17db2d8f8af6/). Although it might not be the most recent: @lynwilhelm can you make sure the right one is linked here? 
## Reproduction

_A minimal example that exhibits the behavior._

## Environment

Looks like this on chrome, safari and edge

**Comment by meganrm** [comment]
I think what happened here is the "share trajectory" input is left justified to show the time param and that style got applied to the other modal too

**Comment by meganrm** [comment]
it also look like there is an extra border

**Comment by lynwilhelm** [comment]
Yes, that is the most current design. I am not partial to the hint text being a URL... or "Start typing..." but yes, it should be left justified. After the user input a URL however, I think it could be useful for the user to be able to see the end of that string (filename). I don't think that would require a right justify though.

**Comment by meganrm** [comment]
> Yes, that is the most current design. I am not partial to the hint text being a URL... or "Start typing..." but yes, it should be left justified. After the user input a URL however, I think it could be useful for the user to be able to see the end of that string (filename). I don't think that would require a right justify though.

Thanks! what should the hint text be? 

This is what it looks like when you enter a url, they can be very long. we could pull out the file name and put it under the input box. For now I'm going to make it look like the current design (plus any change in the hint text you decide on). Let me know if you think we should make any other changes

<img width="665" alt="Screenshot 2024-02-15 at 9 37 14 AM" src="https://github.com/simularium/simularium-website/assets/5170636/18303bf7-252f-42ed-9d65-f53843363b3c">
