### ISSUE TITLE
Wrong colors when loading files with different agent names locally

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#490]
## Description
When successively loading local files with different agent types, the colors sometimes load incorrectly.

## Expected Behavior
Colors should load correctly no matter which file was previously loaded.

## Reproduction
1. download [hemoglobin 10ms](https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/hemoglobin_binding_10ms.simularium) and [hemoglobin 30ms](https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/hemoglobin_binding_30ms_corrected.simularium)
2. Go to https://simularium.allencell.org/viewer
3. Load one file then the other (locally, by drag/drop or file dialog). The second file to load has the wrong colors for agents (usually some of them are yellow) but the left panel still has the correct colors for them (reds and blue).
4. Load the same file twice and there's no problem. I've also tried with loading different files with the same agent names, and there's no problem. It only happens if the agent names are different.

## Environment
Production, Firefox, MacOS

**Comment by blairlyons** [comment]
This is needed for work on iPub so high priority

**Comment by interim17** [comment]
For context for anyone looking at this, I'm pretty sure it's a viewer bug and not in website, because the color swatches on the left panel are correct, and I can recreate it in the test bed. Poking around now.
