### ISSUE TITLE
No cookies popup in embeds

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-website#537]
## Use Case
As a user embedding the viewer in another webpage, I don't want the cookies popup appearing in every instance of the viewer on my website every time it loads.

## Acceptance Criteria
When a link starts with `https://simularium.allencell.org/embed?...` the cookies popup is not triggered (because cookies are not saved).

**Comment by blairlyons** [comment]
@thao-do [this is the page](https://simularium.github.io/subcell-website/) where I'm testing embeds, and here's the iframe code:
`<iframe src="https://simularium.allencell.org/embed?trajUrl=https://readdy-working-bucket.s3.us-west-2.amazonaws.com/outputs/actin_compression_cytosim_readdy.simularium&t=199" frameborder="0" allowfullscreen></iframe>`

**Comment by thao-do** [comment]
I have altered the cookie banner trigger condition - it's no longer shown when I open the github page.
@blairlyons can you double check?

**Comment by thao-do** [comment]
You might want to make a separate ticket for the small screen warning dialog by the way

**Comment by blairlyons** [comment]
It works! Thanks!!
